# Suspend screen after 45 minutes, which should trigger be detected by xss-lock and get a trigger with light-locker
Section "ServerFlags"
	Option "StandbyTime" "2700"
	Option "SuspendTime" "2700"
	Option "OffTime" "2700"
EndSection
