# Suspend screen after 45 minutes, which should trigger be detected by xss-lock and get a trigger with light-locker
Section "ServerFlags"
	Option "StandbyTime" "45"
	Option "SuspendTime" "45"
	Option "OffTime" "45"
EndSection
